batch_size: 256
cores: 2
cuda: 0
env_name: Ant-v2
eval: true
exp_id: do
expl_noise: 0.1
gamma: 0.99
hidden_size: 256
lr: 0.0003
noise_clip: 0.5
noise_type: action
num_steps: 3000000
param_noise_mean: 0
param_noise_std: 0.01
policy_freq: 2
policy_noise: 0.2
replay_size: 1000000
save_interval: 2000
seed: 2021
start_steps: 10000
tau: 0.005
updates_per_step: 1
