alpha_embedding: false
alpha_optim: adam
batch_size: 256
clip_grad_norm: 0.05
cores: 2
cuda: 0
env_name: Hopper-v2
eval: true
exp_id: hopper
gamma: 0.99
hidden_size: 256
log_alpha_max: 0
log_interval: 2500
lr: 0.0003
kl_replay_size: 200000
meta_Q: false
meta_alpha: 1
meta_grad_decay_coef: 0.0
meta_lr: 3e-4
meta_obj_s0: true
meta_train_interval: 1
num_steps: 1000000
replay_size: 1000000
resample: true
rmsprop_eps: 1e-12
save_interval: 1000
seed: 2021
start_steps: 10000
target_update_interval: 1
tau: 0.005
updates_per_step: 1
